# Generated by Django 5.2.7 on 2025-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_alter_ebook_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='accent',
            field=models.CharField(choices=[('us', 'US English'), ('uk', 'British English')], default='us', max_length=2),
        ),
        migrations.AddField(
            model_name='ebook',
            name='voice_style',
            field=models.CharField(choices=[('storytelling', 'Storytelling (Natural)'), ('narration', 'Clear Narration'), ('calm', 'Calm & Slow'), ('energetic', 'Energetic')], default='storytelling', max_length=20),
        ),
    ]
