# Generated by Django 5.2.7 on 2025-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0003_ebook_accent_ebook_voice_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='accent',
            field=models.CharField(choices=[('us', 'US English'), ('uk', 'British English'), ('au', 'Australian English'), ('ca', 'Canadian English'), ('in', 'Indian English'), ('ie', 'Irish English'), ('za', 'South African English'), ('nz', 'New Zealand English')], default='us', max_length=2),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='voice_style',
            field=models.CharField(choices=[('storytelling', 'Storytelling (Natural)'), ('narration', 'Clear Narration'), ('calm', 'Calm & Slow'), ('energetic', 'Energetic'), ('dramatic', 'Dramatic'), ('whisper', 'Whisper'), ('excited', 'Excited'), ('monotone', 'Monotone'), ('formal', 'Formal')], default='storytelling', max_length=20),
        ),
    ]
