# Generated by Django 5.2.7 on 2025-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0005_ebook_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='lyrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
