# Generated by Django 5.2.7 on 2025-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0006_ebook_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='background_animation',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/animations/'),
        ),
    ]
