# Generated by Django 5.2.7 on 2025-11-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0007_ebook_background_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='background_voice',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/audio/'),
        ),
    ]
