# Generated by Django 5.2.7 on 2025-11-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0008_ebook_background_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='background_animation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='background_voice',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pdf_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
