# Generated by Django 5.2.7 on 2025-11-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_alter_ebook_accent_alter_ebook_voice_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
